cache:
  directories:
    - $HOME/.composer/cache

language: php

matrix:
  include:
    - php: 7.1
      env: LARAVEL='5.6.*'
    - php: 7.1
      env: LARAVEL='5.7.*'
    - php: 7.2
      env: LARAVEL='5.6.*'
    - php: 7.2
      env: LARAVEL='5.7.*'
  fast_finish: true

before_script:
    - composer config discard-changes true

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" --no-interaction --no-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
